---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=5.0.0"

  - name: community.docker
    version: ">=3.0.0"
